site_name: Belvaio Request Id
site_description: An aiohttp utils to track request journey between services.

theme:
  name: 'material'

repo_name: belvo-finance/belvaio-request-id
repo_url: https://github.com/belvo-finance/belvaio-request-id
edit_uri: ""


nav:
  - Introduction: 'index.md'
  - Middleware: 'middleware.md'
  - Logging: 'logging.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc
